### ISSUE TITLE
[enhancement] Receive events in D

### ISSUE THREAD

**Issue by MoritzMaxeiner** [filcuc/dqml#9]
Looking at the examples I figured out how to send signals to QML, but not the other way around. If it not implemented, I would like to request it. My use-case:
1. D: Instantiate a (generic) controller `logic` (D class inheriting QObject) and expose it via `engine.rootContext.setContextProperty`
2. QML: Dynamically create a new QML component `chatWindow`, fetch a specialised controller `chat` (D class inheriting QObject) from `logic` and pass it to `chatWindow` as one of its initial properties
3. QML: `chatWindow` registers itself with `chat` via one of the latter's methods
4. D: In that registration, `chat` binds to `chatWindow`'s `destroyed` signal a callback that destroys `chat` itself

The result: When `chatWindow` gets destroyed the corresponding `chat` gets destroyed automatically.

Sadly, `Component.onDestruction` cannot be used in this context, as that would result in `chat`being destroyed while the destructor for `chatWindow` is still running, causing a bunch of QML `null` type errors, one for each reference to `chat` in `chatWindow`.

Now the first two steps are easy to do with what `dqml`currently has. However, I'm at a loss on how to accomplish the last two steps without modifying Dotherside/dqml.

**Comment by MoritzMaxeiner** [comment]
I've got the functionality working with https://github.com/Calrama/DOtherSide/commit/efa6907f8df50f308684e4a291a58584a65940f3 and https://github.com/Calrama/dqml/commit/8560f30729dd49cbbf6d3ee50fbd67bb7c20b136, but it's still missing some syntactic sugar.

**Comment by filcuc** [comment]
Sorry for the delay but been busy on my daily job. I think you're going in the wrong directions:
1) Currently you can connect in both direction in qml and dotherside
From D to QML

```
 ChatWindow {
  property QtObject chat: logic.chat
  Connection {
    target: chat
    onChatSignalChanged: console.log("Changed"
  }
}
```

From QML to D:

```
ChatWindow {
  property QtObject chat: logic.chat
  Component.onDestruction: chat.handleDestruction()
}
```

**Comment by MoritzMaxeiner** [comment]
No problem, I just had quite a bit of time to tackle this: 
The problem with `Component.onDestruction` is that it gets executed before that QObject instance is actually destroyed. Using that method will lead to the `chat` being destroyed too early, as some children of `ChatWindow` are still referring to some of `chat`s properties. From what I was able to gather, the _only_ way to get signalled _after_ `ChatWindow` and all of its children are gone (and thus no more references to `chat` exist on the QML side) is to connect to `ChatWindow`s `destroyed` signal. This, however, cannot be done in QML as the signals are blacklisted.

**Comment by filcuc** [comment]
wait i'm writing you all the possibilities

**Comment by filcuc** [comment]
Regarding your destruction problem you'll not solve anything with your patch. For your problem there's could be lots of solutions
1) Ideally you should execute the following code however qml doesn't allow it

```
ChatWindow {
  ...
  property QtObject chat: logic.chat
  ...
  onDestroyed: logic.removeChat(chat)
}
```

This is not valid code because QML doesn't allow to execute code in the destroyed

2) Given that (1) is not feasible another way is to not change anything in DOtherSide and solve it yourself by handling nullness in QML

```
ChatWindow {
  property QtObject chat: logic.chat
   Text { id: text }
  states: State {
    when: chat != null
   PropertyChanges { target: text: text: chat.title }
  }
}
```

or 

```
Text { text: chat ? chat.text : ""
```

or 

```
Text { 
  Binding on text {
    when: chat
    value: chat.text
  }
}
```

**Comment by filcuc** [comment]
3) We can enhance the DOtherSide by binding the QObject::deleteLater() and use a sort of "hack".

```
...
Component.onDestruction: logic.deleteChat(chat)
...
```

and in the deleteChat method

```
void deleteChat(QVariant chat) {
   chat.deleteLater()
}
```

In this way you make the event loop spin 1 cycle. And so the you should in theory not see the warning since the chat will be deleted later

**Comment by MoritzMaxeiner** [comment]
Thank you for the information, I did not know about these.

> Regarding your destruction problem you'll not solve anything with your patch

Not sure what you mean, because it seems to work perfectly: I bind a QtSlot method on the D side to the QML's `destroyed`  signal. As soon as the QML object gets destroyed, the D method gets called.
EDIT: (I added chat to the GC's roots and made it not moveable)

**Comment by filcuc** [comment]
4) Another solution, but _more_ complex, is to introduce support for object ownership. In your use case basically in C++ i would have used 

```
QQmlEngine::setObjectOwnership(chat, QQmlEngine::JavascriptOwnership 
```

However this is not trivial to implement in the bindings. For a good solution we must 
1) Create a sort of manager for object created from D but that you don't want to handle (in this way the object is not garbage collected from D)
2) Bind the destruction of the object C++ object  to the release of this sort of manager

**Comment by filcuc** [comment]
> Regarding your destruction problem you'll not solve anything with your patch
> Sorry i thinked that you wanted to try to connect to the destroyed signal from QML but this is not allowed. The patch didn't show you app code so basically your solution works since you worked around the limitations of the qml signal connections.

In these weeks i'll be home from xmas vacations and so i've some time for pushing forward the bindings and DOtherSide lib ( i want to give support for creating custom QObjects from D/Nim and make them instantiable in QML).

Give me a day or two for reviewing your patch. I think that i'll integrate it because can be usefull also for connecting signals/slots between objects in the D/Nim side. So between two QObjects in the D side.

Thank you again for inputs

**Comment by MoritzMaxeiner** [comment]
Okay, thank you for the explanation.

> The patch didn't show you app code so basically your solution works since you worked around the limitations of the qml signal connections.

Sorry about that. This is a mostly stripped-down gist about connecting to the `destroyed` signal: https://gist.github.com/Calrama/7a02d7a533145ab95b5c
(It just needs syntactic sugaring regarding generation of the signal names)

**Comment by Calrama** [comment]
Just cleaned up the example a bit, should be readable now. The "send" Button has been missappropriated to show what I mean: Clicking it first destroys the chat window, after which the `destroyed` signal is used to make the D controller destroy itself.

**Comment by MoritzMaxeiner** [comment]
Looking at the alternatives:
2) That seems viable, but also like one has to look out for several things to get right. I'm new to QML and I would like to have as little logic there as possible. Dealing with nullness in Javascript is not something I want to do for long.
3) If I understand the relevant docs correctly, while that does give me the guarantee in being run after the chat window has been destroyed, it doesn't say how much "after". I also want the chat controller cleaned up as soon as possible.
4) That does sound interesting, but I prefer clear boundaries between the languages regarding memory management and where cross-references are necessary I want to control them manually.

All in all I still think binding to the `destroyed` signal is - for my (albeit niche) use case - the best solution. However, since you did not seem to be particularly fond of it, I would like to ask this: If I were to add the required syntactic sugar, would you be willing to pull this (if it passes technical correctness, of course) in a PR (I don't want to allocate the time if you don't want it in anyway)?

**Comment by filcuc** [comment]
As i said you i'll review your patch tomorrow and generally yes i'll willing to integrate signal/slots connection from the binded language layer. This is on my todo list since i would like to support QObject to QObject connections in the D/Nim layer.
Just to be clear i'm not against your patch (since it's something i want to do anyway) i'm not fond of your solution since it's not so common. I've some experience in QML and so that's the reason of my skepticism. Even if we were in C++ i would find unusual to pass a QML object  to the C++ layer and connect signals from there. This is usually the wrong way to do things. Usually the QML layer should be passive and react to changes in the C++ layer and not the other way around. i'll reply to your points given my experience:
2) You have to handle nullness in QML. You'll find out soon or later. It happens often by using loaders and it's very common. The javascript v4 engine is optimize for simple expression in binding like "chat ? char.text : "" ". Furthermore you'll have to handle often with items in ListViews or TableViews
3) It'll be executed in the next event loop cycle. It's pretty clear "when" it will be executed and it's the correct way to delete a QObject in a slot.

**Comment by MoritzMaxeiner** [comment]
Ok, sorry for misunderstanding. I've opened the relevant PRs, the "misc" ones are just things I added for debugging purposes / found interesting.

Thank you for humouring (and correcting) me, as well as sharing your experience, I will take what you wrote into account and use passing objects from QML to D sparingly.
